name: Build Python Package and Docker Image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Python Package and Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build package (wheel and sdist)
        run: |
          pip install build
          python -m build
      - name: Build Docker image
        run: |
          docker build -t ec2-backup-tool .
