name: Gitleaks Secret Scan

on:
  workflow_run:
    workflows: ["Bandit Security Scan"]
    types:
      - completed

jobs:
  gitleaks:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2.3.6
        with:
          args: "detect --source=. --no-git --report-format sarif --report-path gitleaks.sarif"
