name: SonarCloud Analysis

on:
  workflow_run:
    workflows: ["Test Python Code"]  # Matches your test job name
    types:
      - completed

jobs:
  sonarcloud:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Install coverage
        run: pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ebs_snapshot_cli_app \
            -Dsonar.organization=naserraoofi \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
